# --- Configuração do Banco de Dados MySQL (Ativado) ---
spring.datasource.url=jdbc:mysql://localhost:3306/bittint_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Esta linha instrui o Hibernate a criar/atualizar as tabelas no MySQL
# com base nas suas classes @Entity.
spring.jpa.hibernate.ddl-auto=update

# Esta linha mostra no console os comandos SQL que o Hibernate está executando.
spring.jpa.show-sql=true